version: "3.7"

services:
  scrapper:
    container_name: linden-honey-go-scraper
    image: solairerove/linden-honey-go-scraper
    build: .
    ports:
      - 8080:8080
    networks:
      - internal

networks:
  internal:
    driver: bridge
