version: "3.7"

services:
  scrapper:
    container_name: linden_honey_scraper_go
    image: solairerove/linden_honey_scraper_go
    build: .
    ports:
      - 8080:8080
    networks:
      - internal

networks:
  internal:
    driver: bridge
